### ISSUE TITLE
Please add compile time switches to disable/enable DSSI, VST, LV2

### ISSUE THREAD

**Issue by yurivict** [DISTRHO/DPF-Plugins#12]
Users should be able to choose which plugins types they would like to use, and not build something that they don't need.

**Comment by falkTX** [comment]
I had this behavior before, but disagree with it.
You always end up compiling stuff from source that you do not really need. (do you use the entire of ardour? so why build the entire codebase?)

Partially installing what you need is easy, since the plugin type is on the binary filesnames.
This is exactly what the build scripts for windows and mac make use of, they do not ship with ladspa or dssi plugins.
